-- consumer types
INSERT INTO
	CONSUMER_TYPE_LOOKUP (ID, CONSUMER_NAME)
VALUES
	(1, 'service');

INSERT INTO
	CONSUMER_TYPE_LOOKUP (ID, CONSUMER_NAME)
VALUES
	(2, 'canaries');

-- apis
INSERT INTO
	API_LOOKUP (API_NAME, API_GATEWAY_ID)
VALUES
	('demo-api', 'abcdefg123456');

-- endpoints
INSERT INTO
	API_ENDPOINT_LOOKUP (ENDPOINT_NAME, API_LOOKUP_ID)
VALUES
	('/api/v1/demo', 1);
