CREATE TABLE api_lookup (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	api_name varchar(255) NOT NULL,
	api_gateway_id varchar(16)
);

CREATE TABLE api_endpoint_lookup (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	api_lookup_id int REFERENCES api_lookup(id),
	endpoint_name varchar(255)
);

CREATE TABLE consumer_type_lookup (
	id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,
	consumer_name varchar(255)
);
-- auto generate primary keys for table
CREATE TABLE tokens (
	id SERIAL PRIMARY KEY,
	api_lookup_id int REFERENCES api_lookup(id),
	api_endpoint_lookup_id int REFERENCES api_endpoint_lookup(id),
	http_method_type varchar(6),
	environment varchar(255),
	consumer_name varchar(255),
	consumer_type_lookup int REFERENCES consumer_type_lookup(id),
	requested_by varchar(255),
	authorized_by varchar(255),
	date_created timestamp NOT NULL,
	expiration_date timestamp NULL,
	enabled boolean NOT NULL
);