// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TokenAdministrationApi.V1.Infrastructure;

#nullable disable

namespace TokenAdministrationApi.V1.Infrastructure.Migrations
{
    [DbContext(typeof(TokenDatabaseContext))]
    [Migration("20251125151314_AddApiGatewayIdToApiLookup")]
    partial class AddApiGatewayIdToApiLookup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TokenAdministrationApi.V1.Infrastructure.ApiEndpointNameLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiEndpointName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint_name");

                    b.Property<int>("ApiLookupId")
                        .HasColumnType("integer")
                        .HasColumnName("api_lookup_id");

                    b.HasKey("Id");

                    b.ToTable("api_endpoint_lookup");
                });

            modelBuilder.Entity("TokenAdministrationApi.V1.Infrastructure.ApiNameLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiGatewayId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_gateway_id");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_name");

                    b.HasKey("Id");

                    b.ToTable("api_lookup");
                });

            modelBuilder.Entity("TokenAdministrationApi.V1.Infrastructure.AuthTokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiEndpointNameLookupId")
                        .HasColumnType("integer")
                        .HasColumnName("api_endpoint_lookup_id");

                    b.Property<int>("ApiLookupId")
                        .HasColumnType("integer")
                        .HasColumnName("api_lookup_id");

                    b.Property<string>("AuthorizedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authorized_by");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consumer_name");

                    b.Property<int>("ConsumerTypeLookupId")
                        .HasColumnType("integer")
                        .HasColumnName("consumer_type_lookup");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_created");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("HttpMethodType")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("http_method_type");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_by");

                    b.HasKey("Id");

                    b.HasIndex("ApiEndpointNameLookupId");

                    b.HasIndex("ApiLookupId");

                    b.HasIndex("ConsumerTypeLookupId");

                    b.ToTable("tokens");
                });

            modelBuilder.Entity("TokenAdministrationApi.V1.Infrastructure.ConsumerTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("consumer_name");

                    b.HasKey("Id");

                    b.ToTable("consumer_type_lookup");
                });

            modelBuilder.Entity("TokenAdministrationApi.V1.Infrastructure.AuthTokens", b =>
                {
                    b.HasOne("TokenAdministrationApi.V1.Infrastructure.ApiEndpointNameLookup", "ApiEndpointNameLookup")
                        .WithMany()
                        .HasForeignKey("ApiEndpointNameLookupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TokenAdministrationApi.V1.Infrastructure.ApiNameLookup", "ApiLookup")
                        .WithMany()
                        .HasForeignKey("ApiLookupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TokenAdministrationApi.V1.Infrastructure.ConsumerTypeLookup", "ConsumerTypeLookup")
                        .WithMany()
                        .HasForeignKey("ConsumerTypeLookupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiEndpointNameLookup");

                    b.Navigation("ApiLookup");

                    b.Navigation("ConsumerTypeLookup");
                });
#pragma warning restore 612, 618
        }
    }
}
